# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MasiPlot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Masiplot(object):
    def setupUi(self, Masiplot):
        Masiplot.setObjectName("Masiplot")
        Masiplot.resize(1274, 750)
        Masiplot.setMinimumSize(QtCore.QSize(640, 480))
        Masiplot.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Masiplot)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(17)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tLabel = QtWidgets.QLabel(self.groupBox)
        self.tLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.tLabel.setObjectName("tLabel")
        self.gridLayout_2.addWidget(self.tLabel, 0, 0, 1, 1)
        self.tField = QtWidgets.QLineEdit(self.groupBox)
        self.tField.setMinimumSize(QtCore.QSize(0, 0))
        self.tField.setObjectName("tField")
        self.gridLayout_2.addWidget(self.tField, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.nuMinLabel = QtWidgets.QLabel(self.groupBox)
        self.nuMinLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.nuMinLabel.setObjectName("nuMinLabel")
        self.gridLayout_2.addWidget(self.nuMinLabel, 0, 3, 1, 1)
        self.nuMinField = QtWidgets.QLineEdit(self.groupBox)
        self.nuMinField.setMinimumSize(QtCore.QSize(0, 0))
        self.nuMinField.setObjectName("nuMinField")
        self.gridLayout_2.addWidget(self.nuMinField, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        self.speciesLabel = QtWidgets.QLabel(self.groupBox)
        self.speciesLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.speciesLabel.setObjectName("speciesLabel")
        self.gridLayout_2.addWidget(self.speciesLabel, 0, 6, 1, 1)
        self.speciesField = QtWidgets.QComboBox(self.groupBox)
        self.speciesField.setMinimumSize(QtCore.QSize(0, 0))
        self.speciesField.setObjectName("speciesField")
        self.gridLayout_2.addWidget(self.speciesField, 0, 7, 1, 1)
        self.pLabel = QtWidgets.QLabel(self.groupBox)
        self.pLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.pLabel.setObjectName("pLabel")
        self.gridLayout_2.addWidget(self.pLabel, 1, 0, 1, 1)
        self.pField = QtWidgets.QLineEdit(self.groupBox)
        self.pField.setMinimumSize(QtCore.QSize(0, 0))
        self.pField.setObjectName("pField")
        self.gridLayout_2.addWidget(self.pField, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.nuMaxLabel = QtWidgets.QLabel(self.groupBox)
        self.nuMaxLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.nuMaxLabel.setObjectName("nuMaxLabel")
        self.gridLayout_2.addWidget(self.nuMaxLabel, 1, 3, 1, 1)
        self.nuMaxField = QtWidgets.QLineEdit(self.groupBox)
        self.nuMaxField.setMinimumSize(QtCore.QSize(0, 0))
        self.nuMaxField.setObjectName("nuMaxField")
        self.gridLayout_2.addWidget(self.nuMaxField, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 5, 1, 1)
        self.cutoffLabel = QtWidgets.QLabel(self.groupBox)
        self.cutoffLabel.setObjectName("cutoffLabel")
        self.gridLayout_2.addWidget(self.cutoffLabel, 1, 6, 1, 1)
        self.cutoffField = QtWidgets.QLineEdit(self.groupBox)
        self.cutoffField.setObjectName("cutoffField")
        self.gridLayout_2.addWidget(self.cutoffField, 1, 7, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.absorptionBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.absorptionBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.absorptionBtn.setObjectName("absorptionBtn")
        self.gridLayout.addWidget(self.absorptionBtn, 0, 0, 1, 1)
        self.emissionBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.emissionBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.emissionBtn.setObjectName("emissionBtn")
        self.gridLayout.addWidget(self.emissionBtn, 1, 0, 1, 1)
        self.lineSurveyBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.lineSurveyBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.lineSurveyBtn.setObjectName("lineSurveyBtn")
        self.gridLayout.addWidget(self.lineSurveyBtn, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exportCSVBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.exportCSVBtn.setObjectName("exportCSVBtn")
        self.gridLayout_3.addWidget(self.exportCSVBtn, 1, 0, 1, 1)
        self.exportPNGBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.exportPNGBtn.setObjectName("exportPNGBtn")
        self.gridLayout_3.addWidget(self.exportPNGBtn, 2, 0, 1, 1)
        self.clearBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.clearBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.clearBtn.setObjectName("clearBtn")
        self.gridLayout_3.addWidget(self.clearBtn, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        self.mplwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout_3.addWidget(self.mplwidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        Masiplot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Masiplot)
        self.statusbar.setObjectName("statusbar")
        Masiplot.setStatusBar(self.statusbar)

        self.retranslateUi(Masiplot)
        QtCore.QMetaObject.connectSlotsByName(Masiplot)
        Masiplot.setTabOrder(self.tField, self.pField)
        Masiplot.setTabOrder(self.pField, self.nuMinField)
        Masiplot.setTabOrder(self.nuMinField, self.nuMaxField)
        Masiplot.setTabOrder(self.nuMaxField, self.speciesField)
        Masiplot.setTabOrder(self.speciesField, self.lineSurveyBtn)
        Masiplot.setTabOrder(self.lineSurveyBtn, self.absorptionBtn)
        Masiplot.setTabOrder(self.absorptionBtn, self.emissionBtn)

    def retranslateUi(self, Masiplot):
        _translate = QtCore.QCoreApplication.translate
        Masiplot.setWindowTitle(_translate("Masiplot", "MasiPlot"))
        self.groupBox.setTitle(_translate("Masiplot", " Parameters"))
        self.tLabel.setText(_translate("Masiplot", "T (K)"))
        self.nuMinLabel.setText(_translate("Masiplot", "Nu_Min"))
        self.speciesLabel.setText(_translate("Masiplot", "Species"))
        self.pLabel.setText(_translate("Masiplot", "P (atm)"))
        self.nuMaxLabel.setText(_translate("Masiplot", "Nu_max"))
        self.cutoffLabel.setText(_translate("Masiplot", "Cutoff"))
        self.groupBox_2.setTitle(_translate("Masiplot", "Plots"))
        self.absorptionBtn.setText(_translate("Masiplot", "Absorption"))
        self.emissionBtn.setText(_translate("Masiplot", "Emission"))
        self.lineSurveyBtn.setText(_translate("Masiplot", "LineSurvey"))
        self.groupBox_3.setTitle(_translate("Masiplot", "GroupBox"))
        self.exportCSVBtn.setText(_translate("Masiplot", "Export as CSV"))
        self.exportPNGBtn.setText(_translate("Masiplot", "Export as PNG"))
        self.clearBtn.setText(_translate("Masiplot", "Clear Plot"))

from matplotlibwidget import MatplotlibWidget
